# Funding configuration for v3-templater
# RSR PLATINUM: Sustainability support

# GitHub Sponsors
github: [hyperpolymath]

# Open Collective
open_collective: v3-templater

# Custom funding links
custom: ["https://hyperpolymath.dev/sponsor"]
