# CodeClimate configuration for v3-templater
# RSR PLATINUM: Code quality gates

version: "2"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 50
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 50
  identical-code:
    enabled: true
    config:
      threshold: 25

plugins:
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc.js
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

exclude_patterns:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "dist/"
  - "coverage/"
  - "node_modules/"
  - "examples/"
  - "docs/"
  - "scripts/"
  - "*.config.js"
